name: Publish Docker image

on:
  workflow_call:

env:
  KO_DOCKER_REPO: ghcr.io/${{ github.repository }}

jobs:
  docker_build:
    runs-on: ["ubuntu-latest"]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Setup ko
        uses: ko-build/setup-ko@v0.9

      - name: Build and push Docker image
        run: ko build --platform linux/amd64,linux/arm64
